//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Labo.Validation.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must be between {FromValue} and {ToValue}..
        /// </summary>
        internal static string BetweenValidationMessage {
            get {
                return ResourceManager.GetString("BetweenValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must be bigger than {Min} length..
        /// </summary>
        internal static string BiggerThanLenghtValidationMessage {
            get {
                return ResourceManager.GetString("BiggerThanLenghtValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; is not a valid credit card number..
        /// </summary>
        internal static string CreditCardValidationMessage {
            get {
                return ResourceManager.GetString("CreditCardValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; is not a valid email address..
        /// </summary>
        internal static string EMailValidationMessage {
            get {
                return ResourceManager.GetString("EMailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must be equal to &apos;{ValueToCompare}&apos;..
        /// </summary>
        internal static string EqualToValidationMessage {
            get {
                return ResourceManager.GetString("EqualToValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must be greater than or equal to &apos;{ValueToCompare}&apos;..
        /// </summary>
        internal static string GreaterThanOrEqualToValidationMessage {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must be greater than &apos;{ValueToCompare}&apos;..
        /// </summary>
        internal static string GreaterThanValidationMessage {
            get {
                return ResourceManager.GetString("GreaterThanValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must be between {Min} and {Max} length..
        /// </summary>
        internal static string LenghtValidationMessage {
            get {
                return ResourceManager.GetString("LenghtValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must be less than or equal to &apos;{ValueToCompare}&apos;..
        /// </summary>
        internal static string LessThanOrEqualToValidationMessage {
            get {
                return ResourceManager.GetString("LessThanOrEqualToValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must be less than &apos;{ValueToCompare}&apos;..
        /// </summary>
        internal static string LessThanValidationMessage {
            get {
                return ResourceManager.GetString("LessThanValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must not be empty..
        /// </summary>
        internal static string NotEmptyValidationMessage {
            get {
                return ResourceManager.GetString("NotEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must not be equal to &apos;{ValueToCompare}&apos;..
        /// </summary>
        internal static string NotEqualToValidationMessage {
            get {
                return ResourceManager.GetString("NotEqualToValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must not be empty..
        /// </summary>
        internal static string NotNullValidationMessage {
            get {
                return ResourceManager.GetString("NotNullValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; is not a valid phone number..
        /// </summary>
        internal static string PhoneNumberValidationMessage {
            get {
                return ResourceManager.GetString("PhoneNumberValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified condition was not met for &apos;{ValueName}&apos;..
        /// </summary>
        internal static string PredicateValidationMessage {
            get {
                return ResourceManager.GetString("PredicateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; is not in the correct format..
        /// </summary>
        internal static string RegexValidationMessage {
            get {
                return ResourceManager.GetString("RegexValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; must be smaller than {Max} length..
        /// </summary>
        internal static string SmallerThanLenghtValidationMessage {
            get {
                return ResourceManager.GetString("SmallerThanLenghtValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{ValueName}&apos; is not a valid url..
        /// </summary>
        internal static string UrlValidationMessage {
            get {
                return ResourceManager.GetString("UrlValidationMessage", resourceCulture);
            }
        }
    }
}
